text = "QTLVZRFNCVAEÅDMBTNÆVXLNCVZABPZXDWWBSHBÅFQNTZRATNYGCBUWFCRJØGROÆÆVATÅWÅQNTCMØTXEVWSÅEFMNØTCAMJDÆÆNNØVADNTZZEÆEJQDNØBKKTSÅBOVÆRZAWERAEÆYÆQNÅPRAEJGRESNØUQRXUAÆTÅOXQRVÅHCATSFQNØECXKWWBSABSBWREAHÆTNYGCKJZÅQSMSTTIOTFQRRØXLFXCGQRNSHOHRTWQRBWÅBIIRVWREAHQRNYFHPÅÅHQKØEVZUÅSBLKSSBZEWMØWEUSBEIÅSBBKJAVZOVTCASNCZZGJGTTIOTVAKJZÅQSTCMØTXOBMLEDVQTYSFRETETTIOTVAEÆFADLRUQROÆDVAEAOBBEÅEYEOÆDHÆRNCVBSACGQRNØRZGÆWDQRÆNFÆVNCWXAPUVCEÆARXAFKCAULSÅXAR"
#text = "TSFZZZMNPSITBXHPSMJLQMAMIVGWURIXFUMAQJICWKIAIIIBNIEJWLLMDTOGFGRUYDXZHVWTULTBXHPSHZLSSEIITHVFPEIITBEDUEKXAOQBQVKQCLGSIXFAXQPVNAEOBFITASNJTYXZDTTOKHQMAMIDXVTEIIMBOEYFVVVQPSFVUNZIYHXYXIMPSMTTVCTWMCPIREIITHVFPEIITKYDNIJLIGPTAVKMFLSJIHUSPDVVMINOULVNVIZOVVZCLLSPPVZANLIUMPETSQVLAARFWKAMVTHIEXZENJTYXZIDTMDITEPOSLZPTZCIRYQEWEGZIPECJJZMQSFTIUBVCZONLGKTTPRNBBHNJTYXZDTTOJMPENPRWXLECBXVLBAEFWFYIMPSMTTNOCFBRFXLPVWVWIBCBWJVQPSFVUBAKEPMDITEXFRKMPEGJKVGMRPDMGAMROVVZGOTSFEDXZINBRTBDIWXEIMPENPRWXLECBGPLUEDTEXXAWPSIWTZFCPQJXKRPUEEWBHPVRZHVRPHYCTZLJDVRVSEOULVBZMPTWRZMSEIIWEIGTTXIBBHPNMLL"
l = len(text) - 3

def kasiski():
    for i in range(l):
        cur1 = text[i:i+3]
        #print(cur1, " ", i+1)

        for j in range(i+1, l):
            cur2 = text[j:j+3]
            #print(cur2, " ", j+1)
            if(cur1 == cur2):
                for k in range(j+1, l):
                    cur3 = text[k:k+3]
                    if(cur3 == cur1):
                        print(cur1, " ", i+1)
                        print(cur2, " ", j+1)
                        print(cur3, " ", k+1)
                        return()


kasiski()
