text = "QTLVZRFNCVAEÅDMBTNÆVXLNCVZABPZXDWWBSHBÅFQNTZRATNYGCBUWFCRJØGROÆÆVATÅWÅQNTCMØTXEVWSÅEFMNØTCAMJDÆÆNNØVADNTZZEÆEJQDNØBKKTSÅBOVÆRZAWERAEÆYÆQNÅPRAEJGRESNØUQRXUAÆTÅOXQRVÅHCATSFQNØECXKWWBSABSBWREAHÆTNYGCKJZÅQSMSTTIOTFQRRØXLFXCGQRNSHOHRTWQRBWÅBIIRVWREAHQRNYFHPÅÅHQKØEVZUÅSBLKSSBZEWMØWEUSBEIÅSBBKJAVZOVTCASNCZZGJGTTIOTVAKJZÅQSTCMØTXOBMLEDVQTYSFRETETTIOTVAEÆFADLRUQROÆDVAEAOBBEÅEYEOÆDHÆRNCVBSACGQRNØRZGÆWDQRÆNFÆVNCWXAPUVCEÆARXAFKCAULSÅXAR"
n = 5

for i in range(n):
    s = ""
    j = i
    while j < len(text):
        s += text[j]
        j += n
    print(s)
